var Constants = {
	action: {
		UPDATE_LINE_HEIGHT: "UPDATE_LINE_HEIGHT",
		INSERT_PARAGRAPH: "INSERT_PARAGRAPH",
		DELETE_PARAGRAPH: "DELETE_PARAGRAPH",
		INSERT_FORMAT: "INSERT_FORMAT",
		DELETE_FORMAT: "DELETE_FORMAT",

		UPDATE_SELECTION: "UPDATE_SELECTION"
	}
};

export default Constants;