var Constants = {
	action: {
		UPDATE_LINE_HEIGHT: "UPDATE_LINE_HEIGHT",
		INSERT_PARAGRAPH: "INSERT_PARAGRAPH",
		DELETE_PARAGRAPH: "DELETE_PARAGRAPH",
		INSERT_FORMAT: "INSERT_FORMAT",
		DELETE_FORMAT: "DELETE_FORMAT",

		UPDATE_SELECTION: "UPDATE_SELECTION",
		UPDATE_ANCHOR: "UPDATE_ANCHOR",
		UPDATE_EXTENT: "UPDATE_EXTENT",
		UPDATE_SELECTION_TYPE: "UPDATE_SELECTION_TYPE",
	}
};

export default Constants;